name: Android & iOS

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_RUNNER_DEBUG: true # Enable debug logs

jobs:
  cache-node-modules:
    name: Cache node_modules
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-dependencies
        with:
          lookup-only: true

  code-quality:
    name: Code Quality
    runs-on: ubuntu-22.04
    needs: [cache-node-modules]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-dependencies

      - name: Types check
        run: yarn ts

      - name: Lib build
        run: yarn build

  build-android:
    name: Build Android
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        new_arch_enabled: [ 1, 0 ]
        rn_ver: [nightly, next, 0.72, 0.71, '0.70', 0.69, 0.68, 0.67, 0.66, 0.65] # also, can be any npm tag: 0.71-stable, next, nightly
        exclude:
          - new_arch_enabled: 1
            rn_ver: 0.67
          - new_arch_enabled: 1
            rn_ver: 0.66
          - new_arch_enabled: 1
            rn_ver: 0.65
          - new_arch_enabled: 1
            rn_ver: 0.64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build-app
        with:
          arch: arm64-v8a
          new-arch-enabled: ${{ matrix.new_arch_enabled }}
          rn-ver: ${{ matrix.rn_ver }}
          module-to-install: file:${{ github.workspace }}
          store-artifacts: true
          platform: android
          node-version: ${{ contains(matrix.rn_ver, '0.5') && '14' || contains(matrix.rn_ver, '0.6') && '16' || '18' }}
          java-version: ${{ contains(matrix.rn_ver, '0.5') && '8' || contains(matrix.rn_ver, '0.6') && '11' || '17' }}

  build-ios:
    name: Build iOS
    runs-on: macos-13
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        new_arch_enabled: [ 1, 0 ]
        rn_ver: [nightly, next, 0.72, 0.71, '0.70', 0.69, 0.68, 0.67, 0.66, 0.65] # also, can be any npm tag: 0.71-stable, next, nightly
        exclude:
          - new_arch_enabled: 1
            rn_ver: 0.68
          - new_arch_enabled: 1
            rn_ver: 0.67
          - new_arch_enabled: 1
            rn_ver: 0.66
          - new_arch_enabled: 1
            rn_ver: 0.65
          - new_arch_enabled: 1
            rn_ver: 0.64


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build-app
        with:
          new-arch-enabled: ${{ matrix.new_arch_enabled }}
          rn-ver: ${{ matrix.rn_ver }}
          module-to-install: file:${{ github.workspace }}
          store-artifacts: true
          platform: ios
          node-version: ${{ contains(matrix.rn_ver, '0.5') && '14' || contains(matrix.rn_ver, '0.6') && '16' || '18' }}
          java-version: ${{ contains(matrix.rn_ver, '0.5') && '8' || contains(matrix.rn_ver, '0.6') && '11' || '17' }}
