name: E2E

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/yarn.lock'            # new dependencies was added
      - '**/package.json'         # package.json was changed
      - '**/workflows/e2e.yaml'   # CI pipeline was changed
      - '**/actions/*/action.yml' # e2e CI actions was changed
      - '**/.maestro/**'          # e2e tests were changed
      - '**/src/**'               # js code was changed
      - '**/scripts/**'           # scripts were changed
      - '**/android/**'           # android configuration was changed
      - '**/ios/**'               # ios configuration was changed

  push:
    branches:
      - main
    paths:
      - '**/yarn.lock'            # new dependencies was added
      - '**/package.json'         # package.json was changed
      - '**/workflows/e2e.yaml'   # CI pipeline was changed
      - '**/actions/*/action.yml' # e2e CI actions was changed
      - '**/.maestro/**'          # e2e tests were changed
      - '**/src/**'               # js code was changed
      - '**/scripts/**'           # scripts were changed
      - '**/android/**'           # android configuration was changed
      - '**/ios/**'               # ios configuration was changed


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  E2E_ARCH: x86_64
  E2E_RN_VER_TO_TEST: 73
  E2E_MAESTRO_VER: 1.36.0
  E2E_JAVA_VER: 17

jobs:
  build-android-e2e:
    name: Build e2e android.apk
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        new_arch_enabled: [ 1, 0 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/build-app
        with:
          platform: android
          store-artifacts: true
          android-arch: ${{ env.E2E_ARCH }}
          new-arch-enabled: ${{ matrix.new_arch_enabled }}
          rn-ver: 0.${{ env.E2E_RN_VER_TO_TEST }}
          module-to-install: ${{ github.workspace }}
          node-version: 18
          java-version: ${{ env.E2E_JAVA_VER }}



  build-ios-e2e:
    name: Build e2e ios.app
    runs-on: macos-14
    strategy:
      matrix:
        new_arch_enabled: [ 1, 0 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/build-app
        with:
          platform: ios
          store-artifacts: true
          new-arch-enabled: ${{ matrix.new_arch_enabled }}
          rn-ver: 0.${{ env.E2E_RN_VER_TO_TEST }}
          module-to-install: ${{ github.workspace }}
          node-version: 18



  run-android-e2e:
    name: Run Android E2E
    runs-on: macos-13  # Downgrade to macos-13 to use Intel CPU
    needs: [build-android-e2e]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/run-e2e
        with:
          platform: android
          maestro-version: ${{ env.E2E_MAESTRO_VER }}
          react-native-version: ${{ env.E2E_RN_VER_TO_TEST }}
          android-arch: ${{ env.E2E_ARCH }}
          java-version: ${{ env.E2E_JAVA_VER }}

  run_ios_e2e:
    name: Run iOS E2E
    runs-on: macos-14
    needs: [build-ios-e2e]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/run-e2e
        with:
          platform: ios
          maestro-version: ${{ env.E2E_MAESTRO_VER }}
          react-native-version: ${{ env.E2E_RN_VER_TO_TEST }}
